/**
 * Metadata route that generates sitemap.xml for the static marketplace export.
 *
 * Responsibilities:
 * - include every public page generated by the marketplace site
 * - keep sitemap URLs aligned with the GitHub Pages base path and siteUrl
 */
import type { MetadataRoute } from "next";
import { PLUGINS } from "@/lib/catalog";
import { getAllSkills } from "@/lib/github";
import { buildSiteUrl, buildSkillUrl, getHomeUrl, getRssUrl } from "@/lib/seo";

/** Forces static evaluation for GitHub Pages export. */
export const dynamic = "force-static";

/**
 * Builds sitemap entries for the marketplace home page, RSS feed, and skill pages.
 *
 * @returns Public URLs to include in sitemap.xml.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const skills = await getAllSkills();
  const generatedAt = new Date();

  return [
    {
      url: getHomeUrl(),
      lastModified: generatedAt,
      changeFrequency: "daily",
      priority: 1,
    },
    {
      url: buildSiteUrl("skills/"),
      lastModified: generatedAt,
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: buildSiteUrl("what-are-skills/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: buildSiteUrl("claude-vs-codex/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: buildSiteUrl("guides/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: buildSiteUrl("guides/install-skills-from-github/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: buildSiteUrl("guides/best-ci-cd-skills-for-claude-code/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: buildSiteUrl("guides/why-use-a-skills-marketplace/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: buildSiteUrl("guides/well-documented-case-study/"),
      lastModified: generatedAt,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    ...PLUGINS.map((plugin) => ({
      url: buildSiteUrl(`bundles/${plugin.pluginName}/`),
      lastModified: generatedAt,
      changeFrequency: "weekly" as const,
      priority: 0.85,
    })),
    {
      url: getRssUrl(),
      lastModified: generatedAt,
      changeFrequency: "daily",
      priority: 0.3,
    },
    ...skills.map((skill) => ({
      url: buildSkillUrl(skill.repo.owner, skill.repo.repo, skill.name),
      lastModified: generatedAt,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    })),
  ];
}
