/**
 * Metadata route that generates sitemap.xml for the static marketplace export.
 *
 * Responsibilities:
 * - include every public page generated by the marketplace site
 * - keep sitemap URLs aligned with the GitHub Pages base path and siteUrl
 */
import type { MetadataRoute } from "next";
import { getAllSkills } from "@/lib/github";
import { buildSkillUrl, getHomeUrl, getRssUrl } from "@/lib/seo";

/** Forces static evaluation for GitHub Pages export. */
export const dynamic = "force-static";

/**
 * Builds sitemap entries for the marketplace home page, RSS feed, and skill pages.
 *
 * @returns Public URLs to include in sitemap.xml.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const skills = await getAllSkills();
  const generatedAt = new Date();

  return [
    {
      url: getHomeUrl(),
      lastModified: generatedAt,
      changeFrequency: "daily",
      priority: 1,
    },
    {
      url: getRssUrl(),
      lastModified: generatedAt,
      changeFrequency: "daily",
      priority: 0.3,
    },
    ...skills.map((skill) => ({
      url: buildSkillUrl(skill.repo.owner, skill.repo.repo, skill.name),
      lastModified: generatedAt,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    })),
  ];
}
